name: Autoupdater

# Run every day at 2AM and 2PM
on:
  schedule:
  - cron: "0 2,14 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install and cache PowerShell modules
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v4
        with:
          modules-to-cache: powershell-yaml
          shell: powershell, pwsh

      - name: Run script
        id: checker
        run: ./checker.ps1

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automatic update of ${{ steps.checker.outputs.changed }}
